In [1]:
import pandas as pd
import numpy as npy
import matplotlib as pyplt

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [7]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'n_estimators':[100,1000,2000,3000],
           'criterion':['gini', 'entropy'],
           'max_features':['sqrt', 'log2'],
           'class_weight':['balanced', 'balanced_subsample']}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [100, 1000, 2000, 3000]},
             scoring='f1_weighted', verbose=3)

In [10]:
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,grid_predictions)

from sklearn.metrics import classification_report
clf_report=classification_report(Y_test,grid_predictions)

In [11]:
print(cm)

[[44  1]
 [ 1 74]]

In [12]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("f1_macro values for the best parameter{}:".format(grid.best_params_),f1_macro)

f1_macro values for the best parameter{'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9833333333333335

In [14]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9997037037037036

In [15]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([ 0.61042418,  5.47602525, 11.59805303, 16.97374115,  0.64680152,
        5.77803955, 11.11195326, 16.17683163,  0.73974423,  5.5741653 ,
       10.94265704, 16.42268014,  0.63540845,  5.60834451, 12.00614815,
       18.22917967,  0.97184596,  7.63414025, 15.78388867, 23.25412273,
        0.82810001,  8.17408166, 15.41181769, 23.10280399,  0.93747053,
        8.13057246, 16.15831652, 25.10940547,  1.01871839,  8.07289481,
       15.38395095, 20.68373704]), 'std_fit_time': array([0.06844243, 0.2283973 , 0.07804771, 0.28695608, 0.02130736,
       0.14942106, 0.17951475, 0.10092761, 0.07139398, 0.06019469,
       0.09868471, 0.14221547, 0.0092329 , 0.08462737, 0.26839579,
       0.42287788, 0.13382456, 0.23313529, 0.35593812, 0.37292862,
       0.05676636, 0.17190257, 0.08018731, 0.13899255, 0.05321462,
       0.09596841, 0.25514868, 0.43592343, 0.07084556, 0.29036857,
       0.32517796, 1.46958176]), 'mean_score_time': array([0.09574094, 0.59643259, 1.16648126, 1.77230835, 0.10693417,
       0.65659552, 1.22084723, 1.782302  , 0.05976295, 0.57504563,
       1.09892302, 1.7083477 , 0.103936  , 0.5880374 , 1.20010605,
       1.92181454, 0.06249747, 0.66872997, 1.2787879 , 1.75619564,
       0.09999709, 0.66560493, 1.17366152, 1.87877398, 0.03504581,
       0.58435597, 1.31363311, 1.89994092, 0.099998  , 0.62142777,
       1.193713  , 1.54370275]), 'std_score_time': array([0.01229534, 0.07752417, 0.08316774, 0.2022853 , 0.00244793,
       0.11585444, 0.086032  , 0.06917486, 0.04513165, 0.01419816,
       0.04445434, 0.10311866, 0.00525028, 0.03722535, 0.09217758,
       0.09631464, 0.05228986, 0.07084666, 0.05930392, 0.14842482,
       0.04261766, 0.10009408, 0.06452552, 0.05943251, 0.03884187,
       0.03644209, 0.09181979, 0.15070953, 0.05978412, 0.08750954,
       0.04261759, 0.17184148]), 'param_class_weight': masked_array(data=['balanced', 'balanced', 'balanced', 'balanced',
                   'balanced', 'balanced', 'balanced', 'balanced',
                   'balanced', 'balanced', 'balanced', 'balanced',
                   'balanced', 'balanced', 'balanced', 'balanced',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample',
                   'balanced_subsample', 'balanced_subsample'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'gini', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy', 'entropy', 'entropy', 'entropy', 'gini',
                   'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy', 'entropy', 'entropy'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'sqrt', 'log2', 'log2', 'log2',
                   'log2', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'log2', 'log2',
                   'log2', 'log2', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'log2',
                   'log2', 'log2', 'log2', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                   'log2', 'log2', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[100, 1000, 2000, 3000, 100, 1000, 2000, 3000, 100,
                   1000, 2000, 3000, 100, 1000, 2000, 3000, 100, 1000,
                   2000, 3000, 100, 1000, 2000, 3000, 100, 1000, 2000,
                   3000, 100, 1000, 2000, 3000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 1000}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 2000}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 3000}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 1000}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 2000}, {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 3000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 1000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 2000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 3000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 1000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 2000}, {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 3000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 1000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 2000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 3000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 1000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 2000}, {'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 3000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 1000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 2000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 3000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 1000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 2000}, {'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 3000}], 'split0_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'split1_test_score': array([0.96388889, 0.94546891, 0.94546891, 0.94546891, 0.96388889,
       0.96388889, 0.94546891, 0.94546891, 0.94546891, 0.94546891,
       0.94546891, 0.94546891, 0.96388889, 0.96388889, 0.96388889,
       0.94546891, 0.94546891, 0.96388889, 0.94546891, 0.94546891,
       0.96388889, 0.94546891, 0.96388889, 0.96388889, 0.94546891,
       0.94546891, 0.94546891, 0.94546891, 0.94546891, 0.96388889,
       0.96388889, 0.94546891]), 'split2_test_score': array([0.96457219, 0.96457219, 0.96457219, 0.96457219, 0.9822211 ,
       0.96457219, 0.96457219, 0.96457219, 0.94701493, 0.94701493,
       0.94701493, 0.94701493, 0.96457219, 0.96457219, 0.96457219,
       0.96457219, 0.9822211 , 0.94701493, 0.96457219, 0.96457219,
       0.96457219, 0.96457219, 0.96457219, 0.96457219, 0.96457219,
       0.94701493, 0.94701493, 0.94701493, 0.96457219, 0.96457219,
       0.96457219, 0.96457219]), 'split3_test_score': array([0.98205084, 0.96428571, 0.96428571, 0.96428571, 0.98205084,
       0.96428571, 0.96428571, 0.96428571, 0.96428571, 0.96428571,
       0.96428571, 0.96428571, 0.96428571, 0.96428571, 0.96428571,
       0.96428571, 0.96428571, 0.96428571, 0.96428571, 0.96428571,
       0.96428571, 0.98205084, 0.96428571, 0.96428571, 0.96428571,
       0.98205084, 0.96428571, 0.96428571, 0.98205084, 0.98205084,
       0.96428571, 0.98205084]), 'split4_test_score': array([1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       0.9817282, 1.       , 1.       , 1.       , 1.       , 1.       ,
       1.       , 1.       ]), 'mean_test_score': array([0.98210238, 0.97486536, 0.97486536, 0.97486536, 0.98563217,
       0.97854936, 0.97486536, 0.97486536, 0.97135391, 0.97135391,
       0.97135391, 0.97135391, 0.97854936, 0.97854936, 0.97854936,
       0.97486536, 0.97839515, 0.97503791, 0.97486536, 0.97486536,
       0.97854936, 0.97841839, 0.97854936, 0.97854936, 0.97121101,
       0.97490694, 0.97135391, 0.97135391, 0.97841839, 0.98210238,
       0.97854936, 0.97841839]), 'std_test_score': array([0.01599807, 0.02165885, 0.02165885, 0.02165885, 0.01349148,
       0.01751572, 0.02165885, 0.02165885, 0.02430463, 0.02430463,
       0.02430463, 0.02430463, 0.01751572, 0.01751572, 0.01751572,
       0.02165885, 0.02112529, 0.02131389, 0.02165885, 0.02165885,
       0.01751572, 0.02108133, 0.01751572, 0.01751572, 0.0184071 ,
       0.02431016, 0.02430463, 0.02430463, 0.02108133, 0.01599807,
       0.01751572, 0.02108133]), 'rank_test_score': array([ 2, 18, 18, 18,  1,  4, 18, 18, 26, 26, 26, 26,  4,  4,  4, 18, 15,
       16, 18, 18,  4, 12,  4,  4, 32, 17, 26, 26, 12,  2,  4, 12])}

In [16]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.610424,0.068442,0.095741,0.012295,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,2
1,5.476025,0.228397,0.596433,0.077524,balanced,gini,sqrt,1000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
2,11.598053,0.078048,1.166481,0.083168,balanced,gini,sqrt,2000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
3,16.973741,0.286956,1.772308,0.202285,balanced,gini,sqrt,3000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
4,0.646802,0.021307,0.106934,0.002448,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,1
5,5.778040,0.149421,0.656596,0.115854,balanced,gini,log2,1000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
6,11.111953,0.179515,1.220847,0.086032,balanced,gini,log2,2000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
7,16.176832,0.100928,1.782302,0.069175,balanced,gini,log2,3000,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
8,0.739744,0.071394,0.059763,0.045132,balanced,entropy,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
9,5.574165,0.060195,0.575046,0.014198,balanced,entropy,sqrt,1000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
10,10.942657,0.098685,1.098923,0.044454,balanced,entropy,sqrt,2000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
11,16.422680,0.142215,1.708348,0.103119,balanced,entropy,sqrt,3000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
12,0.635408,0.009233,0.103936,0.005250,balanced,entropy,log2,100,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
13,5.608345,0.084627,0.588037,0.037225,balanced,entropy,log2,1000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
14,12.006148,0.268396,1.200106,0.092178,balanced,entropy,log2,2000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
15,18.229180,0.422878,1.921815,0.096315,balanced,entropy,log2,3000,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
16,0.971846,0.133825,0.062497,0.052290,balanced_subsample,gini,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,15
17,7.634140,0.233135,0.668730,0.070847,balanced_subsample,gini,sqrt,1000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,16
18,15.783889,0.355938,1.278788,0.059304,balanced_subsample,gini,sqrt,2000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
19,23.254123,0.372929,1.756196,0.148425,balanced_subsample,gini,sqrt,3000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,18
20,0.828100,0.056766,0.099997,0.042618,balanced_subsample,gini,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
21,8.174082,0.171903,0.665605,0.100094,balanced_subsample,gini,log2,1000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,12
22,15.411818,0.080187,1.173662,0.064526,balanced_subsample,gini,log2,2000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
23,23.102804,0.138993,1.878774,0.059433,balanced_subsample,gini,log2,3000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
24,0.937471,0.053215,0.035046,0.038842,balanced_subsample,entropy,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.964286,0.981728,0.971211,0.018407,32
25,8.130572,0.095968,0.584356,0.036442,balanced_subsample,entropy,sqrt,1000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,17
26,16.158317,0.255149,1.313633,0.091820,balanced_subsample,entropy,sqrt,2000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
27,25.109405,0.435923,1.899941,0.150710,balanced_subsample,entropy,sqrt,3000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,26
28,1.018718,0.070846,0.099998,0.059784,balanced_subsample,entropy,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,12
29,8.072895,0.290369,0.621428,0.087510,balanced_subsample,entropy,log2,1000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,2
30,15.383951,0.325178,1.193713,0.042618,balanced_subsample,entropy,log2,2000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,4
31,20.683737,1.469582,1.543703,0.171841,balanced_subsample,entropy,log2,3000,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,12